version: "3"

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    tty: true
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=finances
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
    - 9000:80
    depends_on:
      - postgres

volumes:
  postgres: